#!/bin/bash

# project run mode configurations
SLNM_BASEURL="$1"
BUILD_NUMBER=${2:-"0"}
SLNM_TESTING_TIMEOUT=${3:-"1500"}
XDISPLAY=${4:-"$DISPLAY"}
REPTS_PATH=${5:-"build/selenium"}

export ANT_OPTS="-Xms256m -Xmx512m -Xss128k"

#$WORKSPACE/../snap/sbin/do_selenium_testsuites http://demo.partners.boombate.com $BUILD_NUMBER 600 ":1:0"

die() {
    echo $1
    exit $2
}

if [ -z $SLNM_BASEURL ] ; then
    die "$0 selenium_base_url [build_number] [selenium process kill timeout in seconds] [display number, autodetect if empty] [path to selenium report dir]" 1
fi

# xserver parameters
XSCREENS_LIMIT="10"
XVFB_OPTS="-ac"
SLNM_PORT="4444"
XVFB_PID=

# look for needed commands
ls=$(which ls)
ant=$(which ant)
xvfb=$(which Xvfb)
ps=$(which ps)
kill=$(which kill)
grep=$(which grep)
import=$(which import)

echo "check executables"
[ -x "$ls" ]   || exit $LINENO
[ -x "$ps" ]   || exit $LINENO
[ -x "$kill" ] || exit $LINENO
[ -x "$grep" ] || exit $LINENO
[ -x "$ant" ]  || die "ant not found: apt-get install ant" $LINENO
[ -x "$import" ] || echo "import not found: apt-get install imagemagick" $LINENO

IMPORT_OPTS="-window root"
if [ ! "$XDISPLAY" ] ; then
    if [ -x "$xvfb" ] ; then
        echo "look for unused xserver display and selenium port"
        r=0
        while true ; do
            r="$[($RANDOM % $XSCREENS_LIMIT) + 1]"
            [ -z "$($ps ax | $grep $xvfb | $grep ":$r.0")" ] && break
        done
        # set variables
        XDISPLAY=":$r.0"
        SLNM_PORT="$[4444 + $r]"

        echo "start xserver"
        $xvfb $XVFB_OPTS $XDISPLAY &
        XVFB_PID=$!
        $ps $XVFB_PID 2>/dev/null 1>/dev/null || die "xvfb not started" $LINENO
    else
        echo "xvfb not found: disable starting xwindows and import screenshot"
        import=
    fi
else
    echo "Run on $XDISPLAY"
fi

IMPORT_OPTS="-display $XDISPLAY $IMPORT_OPTS"

echo "pass through testsuites and run ones: $SLNM_BASEURL"

export DISPLAY=$XDISPLAY

slnm=
[ -z "$SLNM_BASEURL" ] || slnm="selenium"

$ant version.extra version.build report $slnm \
    -D"build.number=$BUILD_NUMBER" \
    -D"slnm.port=$SLNM_PORT" \
    -D"slnm.url=$SLNM_BASEURL" &
ANT_PID=$!

PS_RC=0
echo "wait for selenium finished successfully"
while (( t < $SLNM_TESTING_TIMEOUT )); do
    sleep 1
    $ps $ANT_PID 2>/dev/null 1>/dev/null
    PS_RC=$?
    [ $PS_RC = 0 ] || break
    (( t++ ))
done

if [ $PS_RC = 0 ] ; then
    echo "process become zombie"
    if [ -x $import ] ; then
        echo "take screenshot $import $IMPORT_OPTS $REPTS_PATH/$test.png"
        $import $IMPORT_OPTS "$REPTS_PATH/$test.png"
    fi
    echo "kill sleep process"
    $kill $ANT_PID
    RC=$LINENO
else
    wait $ANT_PID
    RC=$?
    [ $RC = 0 ]
fi

[ "$XVFB_PID" ] && $kill $XVFB_PID

if [ $RC = 0 ] ; then
    APPVERSION=$(php app/console millwright:version:get --parts=3)
    echo "version: v$APPVERSION"
else
    echo "selenium tests failed: $RC"
fi

exit $RC
